### ISSUE TITLE
Use wso2 v5 parent pom

### ISSUE THREAD

**Issue by darshanasbg** [GDRDABARERA/toml-config-migrator#2]
$subject for https://github.com/GDRDABARERA/toml-config-migrator/blob/d80ca57b743ce77d55ddcac21d4ffb9e4132b92a/pom.xml#L25:L28.

Use
```
    <parent>
        <groupId>org.wso2</groupId>
        <artifactId>wso2</artifactId>
        <version>5</version>
    </parent>
```

**Comment by GDRDABARERA** [comment]
Fixed  with 8fbd75e5f3b9817745ab4158f2e747775c7795e8
